#! usr/bin/env python

l = [[4000, 20], [3500, 10], [1800, 9], [1000, 4], [400, 2], [200, 1]]
n = len(l)
m = []
d = dict()
for i in range(0, n-2):

    for j in range(i+1, n-1):

        for k in range(j+1, n):

            z = l[i][1] + l[j][1] + l[k][1]
            if z <= 20:
                y = l[i][0] + l[j][0] + l[k][0]
                m.append(y)
                h = [l[i][1], l[j][1], l[k][1]]
                d.update({y: h})





print(m)
print("Maximum treasure that u can take is :", max(m))
x = d[max(m)]
print("User should take items of weight: ", x[0],"Kg", ",", x[1],"Kg", " and", x[2], "Kg", "with him !!!")
#print(x)
#print(d)

